import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'hi', 'ta', 'te', 'pa', 'ur', 'mr', 'gu', 'bn', 'ml', 'ne'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? hiText = '',
    String? taText = '',
    String? teText = '',
    String? paText = '',
    String? urText = '',
    String? mrText = '',
    String? guText = '',
    String? bnText = '',
    String? mlText = '',
    String? neText = '',
  }) =>
      [
        enText,
        hiText,
        taText,
        teText,
        paText,
        urText,
        mrText,
        guText,
        bnText,
        mlText,
        neText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // homepage
  {
    'r0xgi8rv': {
      'en': 'Sahi Choice',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'm8mndags': {
      'en': 'Sahi Choice',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8ei2kwoz': {
      'en': 'SAHI DEKHO SAHI CHUNO',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'o63se5rk': {
      'en': 'Search for Retailer, product, brand',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0pd6etma': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'j0iyv3dk': {
      'en': 'Categories',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'x3f26f6w': {
      'en': 'Settings',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'r4trxzqb': {
      'en': 'FAQ',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5oitzlsh': {
      'en': 'About Us',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'z0j02l98': {
      'en': 'Andrew D.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '57j3brwm': {
      'en': 'admin@gmail.com',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '3xacsshx': {
      'en': 'View Profile',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bcsuxnnz': {
      'en': 'Welcome to our Home Page',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'l34012oh': {
      'en':
          'you can explore all the retailers here at one place and check what offer is best for you.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'p9f4ta0c': {
      'en': 'Search for retailers, products & brands',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'r4xnd2rw': {
      'en': ' flyers available',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jkk2eg69': {
      'en': 'Dmart',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'kotoi7e5': {
      'en':
          'App is currently in BETA phase and will be uploading the ocntent with time.. sorry for any inconvience called by us in your Browsing throught the application\ndo provide us with the feedback about the app on:\nyour feedback is important for us.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'sclccsjf': {
      'en': 'feedback',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1d3puewb': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // category
  {
    '0mwzxalb': {
      'en': 'Search for retailers, products & brands',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8b9vs6h3': {
      'en': 'Categories',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vopo7moy': {
      'en': 'Groceries',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'p7nq1shi': {
      'en': 'fruits,Vegetables,leaves',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'pxd3g8zz': {
      'en': 'Packed foods',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'eieew1mj': {
      'en': 'chocolates,bakery,beverages,',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'srnxnbp2': {
      'en': 'Fashion',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'pmoplss0': {
      'en': 'shirts,jeans,shoes',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qhix0u16': {
      'en': 'Electronics',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'du9mhp2t': {
      'en': 'Tv,Mobile,Laptop,home appliances',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '6k21ixeh': {
      'en': 'Dairy Products',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fuf9w0fa': {
      'en': 'milk,cheese,lassi',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qxognu57': {
      'en': 'Household Items',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'izrvc2ai': {
      'en': 'decor,blankets,bedsheets',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2n53eb54': {
      'en': 'health & beauty',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'mpx1yz59': {
      'en': 'soap,shampoo,facewash,creams',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'k5j0bohh': {
      'en': 'laundry & Cleaning',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'agn3fwgz': {
      'en': 'detergent,floor cleaner,tissues',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'g4mqb098': {
      'en': 'Category',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1a4x76us': {
      'en': 'Sahi Choice',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5ldfp7yn': {
      'en': 'SAHI DEKHO SAHI CHUNO',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2n5il0wn': {
      'en': 'Search for Retailer, Product & Brand',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'dfafdan0': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'tbbhhla8': {
      'en': 'Categories',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    't5efgfli': {
      'en': 'Settings',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ndnhfvgp': {
      'en': 'FAQ',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'j199jwkn': {
      'en': 'About Us',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'g9g2a1q0': {
      'en': 'Andrew D.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'gyxz6ou3': {
      'en': 'admin@gmail.com',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'l690pj3r': {
      'en': 'View Profile',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'gdo42g9q': {
      'en': 'Category',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // Permissionspage
  {
    'hu40jm4h': {
      'en':
          'Choose what notifcations you want to recieve below and we will update the settings.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'nu6bkwmz': {
      'en': 'Push Notifications',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'uaxb5d2d': {
      'en':
          'Receive Push notifications from our application on a semi regular basis.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'q9kk1y17': {
      'en': 'Media Access',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bfjr3o2z': {
      'en':
          'We ask this permission to upload your user profile picture.\nYou can enable and disable it.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'hx5siqwe': {
      'en': 'Choose weather you want to activate the locations settings below.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '6eh3xhxh': {
      'en': 'Location Services',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'k9h95ixk': {
      'en':
          'Allow us to track your location, this helps keep track of offers and promotions in your city.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2se59zn4': {
      'en': 'Permission settings',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2gnyynyv': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // settingmain
  {
    '4nn8q8g4': {
      'en': 'Please evaluate your options below.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '39x49k74': {
      'en': 'My profile',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'v34lnwut': {
      'en': 'Permission Settings',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'dmoz1j6y': {
      'en': 'Support & FAQs',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'h5iv0u35': {
      'en': 'About Us',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '398potj8': {
      'en': 'T&C and Privacy Policy',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4rx6kk76': {
      'en': 'Feature Request',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'idhls5hq': {
      'en': 'Log Out',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'p6jukwu1': {
      'en': 'Follow us on',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ef0offcq': {
      'en': 'App Versions',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'umqe1baa': {
      'en': 'V 1.0.1',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'cw2ho5rb': {
      'en': 'Settings',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'pvsdj64m': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // Offers
  {
    'scg69byy': {
      'en': 'Offers',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7zcrkc83': {
      'en': 'Offers',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // editprofile
  {
    '356m5pnb': {
      'en': 'Change your password below:',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xayfh36u': {
      'en': 'Change Password',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2ynhb4d9': {
      'en': 'Edit Profile',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '68kert5x': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // Profilepage
  {
    'srdpp151': {
      'en': 'Profile Page',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0tofi5jp': {
      'en': 'Create your Account\nToday',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'dw9psd5n': {
      'en': 'and Customize your shopping feed\naccording to your preferance',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'k6aud8jy': {
      'en': 'Account Options:',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7sxfrmlo': {
      'en': 'Location',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'u8ejdabo': {
      'en': 'Settings',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '33hwyjhh': {
      'en': 'Tutorial',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rnorxmyj': {
      'en': 'FAQs and support',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jftvq58b': {
      'en': 'Log Out',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'v1et1y5c': {
      'en': 'Follow us on',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'uky3cap0': {
      'en': 'Sahi Choice',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'i9r7h3ke': {
      'en': 'SAHI DEKHO SAHI CHUNO',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qd9m0soi': {
      'en': 'Search for Retailer, Product & Brand',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'r0fcc5g3': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'gz591imo': {
      'en': 'Categories',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'oqqgo25l': {
      'en': 'Settings',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8yc3j5bi': {
      'en': 'FAQ',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0t288eqk': {
      'en': 'About Us',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '29ud1zox': {
      'en': 'Andrew D.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'dloo6r0f': {
      'en': 'admin@gmail.com',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'kkvxj9jv': {
      'en': 'View Profile',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'j1y44s1t': {
      'en': 'Profile',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // trending
  {
    '5mfofgcf': {
      'en': 'Groceries',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ax8eh650': {
      'en': 'Electronics',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'my5l6vcv': {
      'en': 'Fashion',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'an8840xo': {
      'en': 'Trending',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1p0lyni0': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // aboutus
  {
    'rmmv6f8o': {
      'en': 'About us',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'v5en6tmm': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // auth_main
  {
    'ye807ljk': {
      'en': 'Sahi Choice',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'me06hb5s': {
      'en': 'SAHI DEKHO SAHI CHUNO',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'frwmg0vs': {
      'en': 'Welcome',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'gbmphfpj': {
      'en': 'Skip to home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wlm4oxa4': {
      'en': 'Access your account or create a new one below.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'o70m41x6': {
      'en': 'Sign Up',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'zdscztfe': {
      'en': 'Email',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'uy9ki1lt': {
      'en': 'Password',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0mc0kny5': {
      'en': 'Confirm Password',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ye5yq4mu': {
      'en': 'Create Account',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bomy1vhc': {
      'en': 'Or sign up with',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'avm61r59': {
      'en': 'Sign In',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'nsdvs43r': {
      'en': 'Email',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'a1ku0f2n': {
      'en': 'Password',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '9r76bnuc': {
      'en': 'Sign In',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '560ivzj7': {
      'en': 'Forgot Password?',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rrlvj8xk': {
      'en': 'Or sign in with',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'asf6qjvf': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // createProfile
  {
    'flwvoo27': {
      'en': 'Sahi Choice',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'llctbwzy': {
      'en': 'SAHI DEKHO SAHI CHUNO',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xqmfwm4h': {
      'en': 'Create Profile',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'b1fmtvaf': {
      'en': 'Edit your the content below to update your profile data:',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'c70na0l9': {
      'en': 'Add Photo',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vqr7zkto': {
      'en': 'Full Name',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ikb8dsgz': {
      'en': 'Your full name...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '3etvc5ne': {
      'en': 'Male',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4a6yfzey': {
      'en': 'Female',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'n5422dk4': {
      'en': 'Others',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'd9ffzkx0': {
      'en': 'Your Gender',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'lxpsaty6': {
      'en': 'Search for an item...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'by028d6m': {
      'en': 'customer',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xpjq3qzl': {
      'en': 'Retailer',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wlqns0mc': {
      'en': 'wholesaler',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'gfn8ov62': {
      'en': 'Your Role',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ycqqw922': {
      'en': 'Search for an item...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wyuo5au4': {
      'en': 'Short Description',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'k37lv48p': {
      'en': 'A Short description about you...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'm0vny7mv': {
      'en': 'Save Changes',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vce5rn23': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // phonepage
  {
    '9mp8rdi9': {
      'en': 'Sahi Choice',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'kwje40bi': {
      'en': 'SAHI DEKHO SAHI CHUNO',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'hjchvv63': {
      'en': 'Enter your Phone Number',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4gfmxz7q': {
      'en':
          'Enter your number below in order to verify or change your Phone number.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'zriu0bj2': {
      'en': 'Your phone number...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'op93bhim': {
      'en': 'Continue',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xu254xzw': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // verifyPhone
  {
    'ipd5s64g': {
      'en': 'Sahi Choice',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rk37znmg': {
      'en': 'SAHI DEKHO SAHI CHUNO',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '3dlgy9h3': {
      'en': 'Verification Code',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'j551x3zp': {
      'en': 'Enter the 6 digit code that you received at: ',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'nwxzze79': {
      'en': '\nwant to change you number?',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'gad5xmkj': {
      'en': 'Change number',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qbbgrays': {
      'en': 'Verify Code',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2wq3570l': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // ForgotPassword
  {
    'y4zge1n0': {
      'en': 'Sahi Choice',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'sqa89fr6': {
      'en': 'SAHI DEKHO SAHI CHUNO',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qvmt8pup': {
      'en': 'Forgot Password',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vnctyoqm': {
      'en': 'Enter your email below in order be sent a reset password link.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bu0veaym': {
      'en': 'Your email address...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xa0khl2c': {
      'en': 'Send Reset Link',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5euyn1hd': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // supportpage
  {
    'u2iu5l0f': {
      'en': 'Welcome to support',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ghk9b93x': {
      'en': 'How can we help you?',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4edxurde': {
      'en': 'Call Us',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '6zdl0agk': {
      'en': 'Email Us',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'pcyucifk': {
      'en': 'Review FAQ\'s below',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'e7e731nv': {
      'en': 'How do I download and install the Sahi Choice app?',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'cz6aag2w': {
      'en':
          'You can download the Sahi Choice app from the Apple App Store or Google Play Store. Simply search for \"Sahi Choice,\" select the app, and click the download/install button.\nOR',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7g984uzd': {
      'en': '[click here]',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'uevv5vn3': {
      'en': ' To share directly.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'zfjekthl': {
      'en': 'Is there a cost to use the Sahi Choice app?',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'sceqbunh': {
      'en':
          'No, the Sahi Choice app is FREE to download and use. You can browse all the latest deals and promotions from local retailers without any charge.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1r68zit9': {
      'en': 'How do I find deals and promotions on Sahi Choice?',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0x7h557u': {
      'en':
          'After logging into the app, you can view deals and promotions on homepage by browsing through the retailers list and there uploaded flyers or using the search function.\n\nYou can also filter results by location, Category or type of promotion to find the best offers tailored to your interests.(BETA)',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'c4wt8q1b': {
      'en': 'How often are new deals and promotions added to Sahi Choice?',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fshgj7ti': {
      'en':
          'New deals and promotions are added regularly, depending on the participating retailers. We update the app frequently to ensure you have access to the latest offers. You can always check back or enable notifications to stay informed about new deals',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jx80kqjz': {
      'en': 'Is my personal information safe with Sahi Choice?',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'nw0vgtzu': {
      'en':
          'Yes, we take your privacy and data security seriously. Sahi Choice uses advanced security measures to protect your personal information. We comply with all applicable data protection regulations and do not share your data with third parties without your consent.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vsds5jw2': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'cfuuca9c': {
      'en':
          'You can update your profile and preferences by going to the “Settings” or \"Profile\" menu in the app. From there, you can edit your personal information, adjust notification settings, permission, Location and customize your shopping preferences.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'h0ayvjxm': {
      'en':
          'How can I provide feedback or suggest new features for the Sahi Choice app?',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'and59bn3': {
      'en':
          'We value your feedback! Your input helps us improve and enhance the app You can provide suggestions and feedback through the “Feedback” option in the app’s menu or by contacting us directly at  ',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5v77g8pw': {
      'en': ' [Feedback]',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wmhpy22m': {
      'en': 'for assistance',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'b4m1p2j0': {
      'en':
          'How do I report an issue with a deal or promotion I found on Sahi Choice?',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'zkb5psk0': {
      'en':
          'If you encounter an issue with a deal or promotion, such as incorrect information or an expired offer, you can report it through the app. Go to the specific deal and click the “Report” button, or contact our support team at',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ovdxnbhp': {
      'en': '[Support]',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'o0b53271': {
      'en': 'for assistance or create a ticket',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '971foazu': {
      'en': 'Create Ticket',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8227bwb9': {
      'en': 'Chat Now',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    's74a832k': {
      'en': 'Get support',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'tr81416h': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // searchpage
  {
    'twevzdqr': {
      'en': 'Search Page',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '512i7wyn': {
      'en': 'Search for Product, Brand, Category Etc...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'pyrrvaff': {
      'en': 'Option 1',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ctu0twhz': {
      'en': ' search Result',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'u3t1vq9u': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // retailerpage
  {
    'jizfjkev': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // onboardpage
  {
    'xar4upsq': {
      'en': 'Sahi Choice',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'v3qh5r4m': {
      'en': 'All-in-one Offers and promotional App',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'zqlfiyj3': {
      'en': 'Browser Retailers in town',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '9wwwg905': {
      'en':
          'checkout all the retail stores around you for weeking promotions and ',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8ehuh23e': {
      'en': 'Personalized Feed according to your location',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wqxkgqao': {
      'en':
          'We Provide retailer offers according to your locality Accross India',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'klt81gck': {
      'en': 'Smart Shopping with SAHI CHOICE',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'lpdz641e': {
      'en':
          'Plan ahead and save time! With our app, you can organize your shopping list and avoid visiting multiple stores.\n Shop smart, shop fast!',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '06zc2sx8': {
      'en': 'Skip directly to flyers',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '33fir874': {
      'en': 'Create Account or Sign in',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xkl1edw6': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // ticketpage
  {
    'thiihjvg': {
      'en': 'Create a Ticket Report',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'q8zcsjxx': {
      'en': 'Fill out the form below to submit a ticket.',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'hoqcljg6': {
      'en': 'Report your Bug or issue...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'mb5vzvoc': {
      'en': 'Short Description on issue you are facing...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'e6100t0o': {
      'en': 'upload a Screenshot',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'm2uezubw': {
      'en': 'Submit Ticket',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'r6znh2ft': {
      'en': 'Create Ticket ',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'n0djalcx': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // flyerpage
  {
    '0zsgeoem': {
      'en': 'Explore more offers',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'cqtuiuey': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // proex
  {
    'mrhp1rl3': {
      'en': 'check.io',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'uga04b55': {
      'en': 'Platform Navigation',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '69ssu0s6': {
      'en': 'Dashboard',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'dr8ot5rd': {
      'en': 'Chats',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jqxa0pit': {
      'en': 'Projects',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ofcu9ft8': {
      'en': 'Recent Orders',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '3rgqdc90': {
      'en': '12',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'x120ay57': {
      'en': 'Settings',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'iio0nig0': {
      'en': 'Billing',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xk0anbap': {
      'en': 'Explore',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'tkq97gzr': {
      'en': 'Casper Ghost',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'r81ikgd1': {
      'en': 'admin@gmail.com',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'p3ezcb9u': {
      'en': 'Casper Ghost',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'c6rkbttx': {
      'en': 'casper@ghustbusters.com',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rkx3xyfj': {
      'en': '2,200',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jilbyszk': {
      'en': 'Orders Placed',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'b9cz9nvu': {
      'en': '\$212.4k',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2b7kb60z': {
      'en': 'Money Earned',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5ta4xlwz': {
      'en': 'Change Password',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '6ur027pv': {
      'en': 'Edit Profile',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rxzexwn3': {
      'en': 'Support',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1d3v0xmm': {
      'en': 'Tutorial',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wx1yow7b': {
      'en': 'Submit a Bug',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1cgrb57u': {
      'en': 'Submit a Feature Request',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vkfjmsl6': {
      'en': 'Log Out',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jhkwsikg': {
      'en': 'My Profile',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'osdj6oxk': {
      'en': '__',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // categorypage
  {
    'xp5sd12q': {
      'en': ' Items of this category:',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jjlv0pfo': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // extra
  {
    'grouj620': {
      'en': 'Page Title',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'af5ap2c7': {
      'en': 'Home',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // editProfile_auth_2
  {
    '4g0vs6ji': {
      'en': 'Want to Link or Change your Phone Number',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jyhvy4vo': {
      'en': 'Phone Number',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'pk6soxbc': {
      'en': 'Edit your the content below to update your profile data:',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qdfq8qa6': {
      'en': 'Change Photo',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wdmuu754': {
      'en': 'Full Name',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'pjy2ykvf': {
      'en': 'Your full name...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'q9uf6kpq': {
      'en': 'Consumer',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '3ksyvgeh': {
      'en': 'Retailer',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xwb76gxf': {
      'en': 'Your Role',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2znrzneq': {
      'en': 'Search for an item...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'egxy99tu': {
      'en': 'Male',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    's9mjmb09': {
      'en': 'Female',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'inkgtwsj': {
      'en': 'Other',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'yu05nwvp': {
      'en': 'Your Gender',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xgeqpu1b': {
      'en': 'Search for an item...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'edw4vd56': {
      'en': 'Short Description',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jun6uckj': {
      'en': 'A Short description about you...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // product_component
  {
    'u8yoz6s9': {
      'en': 'Review your Product:',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    's0okfa2c': {
      'en': 'Retailer: ',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7yhxxqac': {
      'en': 'offer valid',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '6etb6iv4': {
      'en': ' TO ',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'orq1y76e': {
      'en': 'BasePrice',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'zv7exp6x': {
      'en': 'After Sale Price',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'iy9b9tlg': {
      'en': 'Close',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qgbwyof4': {
      'en': 'share',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // locationselection
  {
    'irob62pi': {
      'en': 'Update your location here...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'uk8ifvnd': {
      'en': 'State',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wjpjs2m1': {
      'en': 'Please select...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '9kl3kl8d': {
      'en': 'Search for an item...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'n9auv1h7': {
      'en': 'district',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4wvdnep0': {
      'en': 'Option 1',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '19nep5qm': {
      'en': 'Please select...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xjq3gazr': {
      'en': 'Search for an item...',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'w4aseruw': {
      'en': 'Save',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // Miscellaneous
  {
    '65dgkdqi': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xj5ilsha': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'pcioi22f': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'kk4xsyr9': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'pcfhfimu': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rswyvvfi': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'h87bze6d': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'acuia9ou': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8abqv4k8': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vn0igaun': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'dci4d4ti': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ff18a4ub': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ujgcpe95': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jqjepzg2': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qs7o0ct5': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qvr85e9c': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'l584agns': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '19rdub6w': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'phsejdvt': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'u4rl455g': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wt628b8g': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fj4ryofj': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xwza1zt2': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '73ivyidi': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'p6mcanuy': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ocnf10ek': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'aqsel5px': {
      'en': '',
      'bn': '',
      'gu': '',
      'hi': '',
      'ml': '',
      'mr': '',
      'ne': '',
      'pa': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
].reduce((a, b) => a..addAll(b));
